config/routes.rb
Rails.application.routes.draw do

  #root 'top#top'
  #get '/'  => 'top#top'
  root 'aim_room#index'
  get '/'  => 'aim_room#aim_room'
  #get 'aim_room/index'

  
  

  #devise_for :users
  devise_for :users, controllers: {       # ← 恐らく最初は”devise_for:”のみの記載かと
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }, skip: :confirmations
  get 'user/regist_after' => 'user#regist_after'

  post '/user/follow/', to: 'user#follow'
  post '/user/follow_delete', to: 'user#follow_delete'



  get '/top/index'  => 'top#index'
  
  get '/top/index'  => 'top#index'

  get '/top/aim/load_more'  => 'top#load_more'
  post '/top/aim/load_more'  => 'top#load_more'
 
  
  resources :contact, only: [:new, :create]

  get 'pricing'  => 'footer#pricing'
  get 'business'  => 'footer#business'
  get 'sctl'  => 'footer#sctl'
  get 'policy'  => 'footer#policy'
  get 'terms'  => 'footer#terms'
  #get 'aim/search'
  
  #resources :aim, only: [:new, :create, :edit, :aim, :search]
  resources :aim, only: [:new, :create, :edit, :aim]
  
  #get 'aim'  =>'aim#aim'
  #get '/search/:id', to: 'aim#search'
  #get 'create'  =>'aim#create'

  get '/aim/:id', to: 'aim#aim',as: 'aim'
  get 'search'  => 'aim#search'
  post '/aim/create/', to: 'aim#create'
  get '/aim/edit/:id'  =>'aim#edit'
  post '/aim/new_confirm/'  =>'aim#confirm'
  #patch '/aim/update/:id', to: 'aim#update'
  post '/aim/update/:id', to: 'aim#update'
  post '/aim/delete/:id', to: 'aim#delete'

  post '/aim/like/', to: 'aim#like'
  post '/aim/like_delete/', to: 'aim#like_delete'

  resources :user, only: [:new, :create, :edit, :aim]
  get 'new_user'  => 'user#new_user'
  get 'mypage'  => 'user#mypage'
  get 'account_delete'  => 'user#account_delete'
  #get 'top'  => 'top#top'

  #get 'mypage'  => 'user#mypage'
  get '/user/:username', to: 'user#mypage'
  
  #resources :setting, only: [:update_password]
  get 'setting'  => 'setting#setting_page'
  post '/setting/update_mail/:id', to: 'setting#update_mail'
  post '/setting/update_username/:id', to: 'setting#update_username'
  post '/setting/update_password/:id', to: 'setting#update_password'
  patch '/setting/update_password/:id', to: 'setting#update_password'
  post '/setting/delete_user/:id', to: 'setting#delete_user'

  post '/setting/icon_type_change/:id', to: 'setting#icon_type_change'
  get '/setting/user/custom_img'  => 'setting#custom_img'
  post '/setting/upload_img/:id', to: 'setting#upload_img'

  #resources :notifications, only: [:index, :new, :create, :check]
  resources :notifications, only: [:index, :new ,:create]
  patch '/notifications/check', to: 'notifications#check'
  post '/notifications/check', to: 'notifications#check'
  post '/notifications/delete/:id', to: 'notifications#delete'
  #post '/notifications/create/', to: 'notifications#create'

  get '/llm'  => 'llm#index'
  post "/ai/generate/", to: "llm#generate"

  get '/play'  => 'play#index'
  post '/play', to: 'play#post'

  get '/sitemap' => 'sitemaps#index' 
end

app/views/shared/_ads-mobile.html.erb
  <div class ="ads-mobile">
      <!-- admax -->
      <script src="https://adm.shinobi.jp/s/af986910ff5906e697d20264a8a10e13"></script>
      <!-- admax -->
  </div>

app/views/shared/_create-edit-header.html.erb
<header class ="create_edit_header">
  <div class ="head-wrap">
    <div class ="svg-wrap">
      <div class="Logo-a">
        <a href="/">
              <%= image_tag 'Logo_White.svg' , class: 'Logo Logo-white' %>
              <%= image_tag 'Logo_Black.svg' , class: 'Logo Logo-black' %>
        </a>
      </div>
    </div>
    <div class="items">
        <button id="submitButton" class="btn btn-warning m-12">公開</button>
    </div>
  </div>
</header>

app/views/shared/_favorite-btn-already.html.erb
<i class="favorite-btn fa-solid fa-heart fa-2xl" style="color: #c8ff00;"></i>

app/views/shared/_favorite-btn.html.erb
<i class="fa-regular fa-heart fa-2xl" style="color: #c7fd08;"></i>

app/views/shared/_favorited-btn-bounce.html.erb
<i class="favorite-btn fa-solid fa-heart fa-2xl fa-bounce" style="color: #c8ff00;"></i>

app/views/shared/_header.html.erb
<header>
<div class ="head-wrap">
<div class ="svg-wrap">
    <!--
    <img src="Logo.png" class="Logo" >
    <span class="LogoTitle" >AimSite</span>
    <%= image_tag(s3_asset_path('Logo.svg'), content_type: 'image/svg+xml') %>
    -->
    <div class="mobile-menu-icon">
      <i class="menu-icon fa-solid fa-bars fa-2xl"></i>
    </div>

    <div class="Logo-a">
    <a href="/" class="Logo_a">
      <!-- 
      <svg viewBox="0 0 3000 250" role="img" aria-labelledby="BAKERY COLNE" class="b-hero-cover03-bg-logo">
        <use xlink:href="<%= s3_asset_path('Logo.svg') %>#Logo"></use>      
        <use xlink:href="/assets/Logo.svg#Logo"></use>
        <use xlink:href="<%= asset_path('Logo.svg') %>#Logo"></use> 
        <use xlink:href="<%= s3_asset_path('Logo.svg') %>#Logo" crossOrigin="Anonymous"></use>  
      </svg>
      
    image_tag(s3_asset_path('Logo.svg'), content_type: 'image/svg+xml', class: 'Logo Logo-white')  
    -->
    <%= image_tag 'Logo_White.svg' , class: 'Logo Logo-white', alt: "Logo_icon" %>
    <%= image_tag 'Logo_Black.svg' , class: 'Logo Logo-black', alt: "Logo_icon" %>
    </a>
    </div>
      
    <!--
    <form method="GET" action="/search" class="SearchForm">
      <input type="text" class="SearchBox" name="word" placeholder="検索">
      <a href="" type="submit" class="SearchBtn"><%= image_tag(s3_asset_path('Logo.svg'), content_type: 'image/svg+xml') %></a>
    </form>
    -->

    <!--
    <% if user_signed_in? %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete ,class: "NewUser_btn btn btn-success mb-12" %><br>
      <%= link_to "マイページ", "/mypage" ,class: "Login_btn btn btn-success mb-12" %>
      <%= link_to "Aim新規作成", "/aim/new" ,class: "NewAim_btn btn btn-success mb-12" %>
    <% else %>
      <%= link_to "ログイン", new_user_session_path ,class: "Login_btn btn btn-warning mb-12" %><br>
      <%= link_to '登録', new_user_registration_path ,class: "NewUser_btn btn btn-success mb-12" %>
    <% end %>
    -->

    <% if !user_signed_in? %>
      <%= link_to "ログイン", new_user_session_path ,class: "Login_btn btn mb-12" %><br>
      <%= link_to 'アカウント作成', new_user_registration_path ,class: "NewUser_btn btn mb-12" %>
    <% end %>
  </div>

<div class ="items">

  <% if user_signed_in? %>
    <%= link_to  "/aim/new" ,class: "newAim-btn btn mb-12" do %>
        <i class="fas fa-edit"></i> Aim作成
    <% end %>
  <% end %>

    <%= link_to  "/llm/" ,class: "goLLM_btn btn mb-12" do %>
        <i class="fas fa-edit"></i> LLM
    <% end %>

    <%= link_to  "/play/" ,class: "goPlay_btn btn mb-12" do %>
        <i class="fas fa-edit"></i> <%= t(:play_btn) %>
    <% end %>

  <form action="/search" method="get" class="search-form">
    <span class="material-symbols-outlined search-form-span" aria-hidden="true">
      search
    </span>
    <input type="search" autocomplete="off" placeholder="エイムを検索" value="" name="word" required="" class="search-form-input">
  </form>
  <button class="search-btn-mini">
    <span class="material-symbols-outlined search-span" aria-label="記事、質問を検索">
      search
    </span>
  </button>
  
  <!-- ログイン中のコンテンツ -->
  <% if user_signed_in? %>
  <div class="notifications-wrap">
    <button tabindex="0" class="notifications-button" id="notifications-button">
      <span class="material-symbols-outlined notifications-span" aria-label="通知">notifications</span>
     
      <% if @nocheck_notification_count > 0 %>
         <p class="badge"> </p>
      <% end %>
      
    </button>
  </div>
  <div class ="user-icon">
    <%= render 'shared/my_user_icon' %>
    
    <!--<div class="dropdown-wrap">
      <a href="/mypage" class="style-6cmdul"><span class="material-symbols-outlined style-uah80t" aria-hidden="true">person</span>マイページ</a>
      <a href="{{ url('/setting') }}" class="style-6cmdul"><span class="material-symbols-outlined style-uah80t" aria-hidden="true">settings</span>設定</a>
      <form method="POST" action="{{ route('logout') }}">@csrf<button type="submit">ログアウト</button></form>
    </div>-->
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />
    <div class="container"> 
      <div class="dropdown-user-icon" id="dropdown-user-icon">
        <!--<a href="/mypage"><i class="bx bx-user"></i>マイページ</a>-->
        <a href="/user/<%= current_user.user_name %>"><i class="bx bx-user"></i>マイページ</a>
        <a href="/setting"><i class="bx bx-cog"></i>設定</a>

<a href="#" onclick="toggleTheme()"><i class="bx bx-adjust"></i>テーマ切替</a>

        <!--link_to "ログアウト", destroy_user_session_path, method: :delete ,class: "NewUser_btn btn btn-success mb-12"-->
        <!--<form name="sample_form_name" method="DELETE" action="<%= destroy_user_session_path %>">
          <a href="javascript:sample_form_name.submit()"><i class="bx bx-log-out"></i>ログアウト</a>
        </form>
        -->
        <%= link_to destroy_user_session_path, method: :delete  do %>
          <i class="bx bx-log-out"></i>"ログアウト"
        <% end %>
      </div>
      <div class="dropdown-notifications" id="dropdown-notifications">
        <p>通知</p><hr>
        <p class="notification-notthing">通知はありません。</p>

        <%= form_with(model: @notifications, url: notifications_check_path, local: true, html:{ name:"notification_check_form" ,class:"edit-form" ,id:"edit-form"}) do |form| %>
        <% end %>

        <% @notifications.each do |nc| %>
          <div class="nc_wrap">
            <div class="nc_img_wrap">
              <%= image_tag '/default_notifications_icon.svg', alt: "img",class: "nc_img", id: "thumbnail-img",loading:"lazy" ,height:"26", width:"26"%>
            </div>
            <a href="<%= nc[:url] %>" class="nc_a_wrap">
              <p><%= nc[:title] %></p>
              <% time = Time.parse(nc[:created_at].to_s); time_jst = time.in_time_zone('Tokyo'); formatted_time = time_jst.strftime('%Y年%m月%d日')%>
              <time datetime="<%= nc[:created_at] %>" class="style-19rsmo4"><%= formatted_time %></time>
              <!--<time datetime="2023-10-23T06:10:16Z" class="style-19rsmo4">2023/10/23 15:10</time>-->
            </a>
          </div>
        <% end %>

        <a href="/notifications" id="to_nc_list"><i class="bx bx-bell"></i>通知一覧を見る</a>
      </div>
    </div>
  </div>
  <% end %>
</div>


</header>

<!--<div class="mobile-search-form" id="mobile-search-form">
  <input type="text" placeholder="Search...">
</div>-->
<form action="/search" method="get" class="mobile-search-form" id="mobile-search-form">
  <span class="material-symbols-outlined search-form-span" aria-hidden="true">
    search
  </span>
  <input type="search" autocomplete="off" placeholder="エイムを検索" value="" name="word" required="" class="search-form-input" id="mobile-search-form-input">
</form>

<script>
document.querySelector('.search-btn-mini').addEventListener('click', function() {
  //this.classList.toggle('active');
  var searchBar = document.getElementById('mobile-search-form');
      searchBar.style.display = (searchBar.style.display === 'none' || searchBar.style.display === '') ? 'block' : 'none';
      document.getElementById('mobile-search-form-input').focus();
});
</script>

<div class="header_tab_menu">
    <a href="/" class="header_tab_menu_a"><button class="tablink btn btn-primary">ホーム</button></a>
    <a href="/aim/new" class="header_tab_menu_a"><button class="tablink btn btn-primary">aim作成</button></a>
    <a href="/llm" class="header_tab_menu_a"><button class="tablink btn btn-primary">LLM</button></a>
    <a href="/play" class="header_tab_menu_a"><button class="tablink btn btn-primary">遊び</button></a>
</div>

app/views/shared/_my_user_icon.html.erb
<button id="header-user-icon-btn" class="header-user-icon-btn" aria-label="メニューボタン">
      <% if current_user.icon_url=="default" %>
            <!--<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M12 12C14.2091 12 16 10.2091 16 8C16 5.79086 14.2091 4 12 4C9.79086 4 8 5.79086 8 8C8 10.2091 9.79086 12 12 12ZM12 14C9.33 14 4 15.34 4 18V20H20V18C20 15.34 14.67 14 12 14Z" fill="currentColor"/>
            </svg>-->
            <img alt="default_user_icon" src="/default_user_icon.png"  class="user-icon_img">
      <% elsif current_user.icon_url=="custom" %>
            <% if current_user&.user_icon_image.attached? %>
                  <%= image_tag current_user.user_icon_image ,class:"user-icon_img", alt: "user-icon_img" %>
            <% else %>
                  <!-- アイコンがアップロードされていない場合の代替コードをここに追加 -->
                  <img alt="default_user_icon" src="/default_user_icon.png"  class="user-icon_img">
            <% end %>
      <% elsif current_user.icon_url=="gravatar" %>
            <img src="https://www.gravatar.com/avatar/<%= Digest::MD5.hexdigest(current_user.email) %>?s=200" alt="User's Gravatar" class="user-icon_img" >
      <% end %>
</button>

app/views/shared/_side-ads.html.erb
<div class ="side-ads-wrap">
    <div class ="ads-PC">
            <div>
                <a href="https://px.a8.net/svt/ejp?a8mat=3TLDN1+9QOCUY+551Y+609HT" rel="nofollow"  id="a8net" aria-label="a8net">
                <img border="0" width="300" height="250" alt="" src="https://www22.a8.net/svt/bgt?aid=231104845589&wid=002&eno=01&mid=s00000023983001009000&mc=1"></a>
                <img border="0" width="1" height="1" src="https://www13.a8.net/0.gif?a8mat=3TLDN1+9QOCUY+551Y+609HT" alt="">
            </div>
            <div>
                <img width="300" height="250" src="/Looking_for_sponsor.svg" alt="">
            </div>
            <div>
                <!-- admax -->
                <script src="https://adm.shinobi.jp/s/7d09a644cd09b9ab364a609d991ffc03"></script>
                <!-- admax -->
            </div>
    </div>
</div>

app/views/shared/_sidemenu.html.erb
<%= stylesheet_link_tag "user-ranking" %>

<div class="Left">
 

  <div class="Left-content">

      <div class="UserRanking_wrap">
            <h4>ユーザーランキング</h4>
            <% 
            #@aa = User.where(id: 1).limit(10)
            @rank_users = User.joins(:aims)
                        .group("users.id")
                        .order("count(aims.id) DESC")
                        .limit(3)
            i=1;
            @rank_users.each do |user|
                @this_user=user
                #user_ranking_user_wrapの子要素のuser_ranking_No_wrapと、user-icon_imgと、hopを横並びにして
                #hopの子要素のuser_ranking_username_wrapとuser_ranking_createNum_wrapとfollow-btnを縦並びにして
                %>
                      <div class="user_ranking_No_wrap"><%= i %></div><% i=i+1; %>
                      <div class="user_ranking_user_wrap">
                          <div class="cont">
                              <%= render 'shared/user_list' %> 
                          </div>
                      </div>
            <% end %>
      </div>
  
<!--
    <% if user_signed_in? %>
        <div class="UserRanking_wrap">
            <h4>ユーザーランキング</h4>
            <% @users_with_duplicated_names.each do |user|%>
                  <a href="/user/<%= user.user_name %>">
                        <p>@<%= user.user_name %><p>
                        <p>記事数：<%= 5 %><p>
                  </a>
                  <button class="follow-btn">フォロー</button>
            <% end %>
            </div>
    <% end %>
-->
    <div class="footer-wrap">
        <hr>
        <div class="link-div"><a href="/pricing" class="contact_link">料金/プラン</a></div>
        <div class="link-div"><a href="/business">ビジネス</a></div>
        <div class="link-div"><a href="/sctl">特定商取引法に基づく表記</a></div>
        <div class="link-div"><a href="/policy">プライバシーポリシー</a></div>
        <div class="link-div"><a href="/terms">利用規約</a></div>
        <div class="link-div"><a href="/contact/new" class="contact_link">お問い合わせ</a></div>
        <label for="lang_select">言語を選択:</label>
        <select id="lang_select">
            <option value="ja">日本語</option>
            <option value="en">English</option>
            <option value="zh-CN">中文</option>
        </select>
        <script>
//画面読み込み時に処理
//$(function(){
// ローカルストレージから値を取得
  //const lang= localStorage.getItem('lang');

  const lang= Cookies.get('lang');

//undefinedならまだcookieにlangが入っていないので、ブラウザの設定言語をcookieに入れる
  if (lang === undefined) {
        console.log("undefinedならまだcookieにlangが入っていないので、ブラウザの設定言語をcookiに入れる")
        // ブラウザの言語設定を取得
        const browser_language = navigator.language; 
        // 言語で条件分岐
        //let browser_lang="jp";
        let browser_lang="ja";
        if (browser_language.startsWith("ja")) {
            //browser_lang = "jp";
            browser_lang = "ja";
        } else if (browser_language.startsWith("en")) { 
            //browser_lang = "en";
            browser_lang = "en";
        } else if (browser_language.startsWith("zh")) {
            //browser_lang = "zh";
            browser_lang = "zh-CN";
        }
        console.log("browser_language:"+browser_language+"・browser_lang:"+browser_lang)
        Cookies.set('lang',browser_lang);
        lang=browser_lang;
  }

  


  //cookieから値を取得
  /*var r = document.cookie.split(';');
    r.forEach(function(value) {
    var content = value.split('=');
    lang=content[1];
    console.log("クッキー:"+content[1]);
    });
    */
  console.log("画面読み込み時の言語："+lang)

    //ドロップダウンの初期値変更
    var lang_select = document.getElementById("lang_select");
    lang_select.value = lang;


  /*if (lang=== 'jp') {
    design_light();
  }else if (lang=== 'en') {
    design_dark();
  }else if (lang=== 'zh'){
    design_dark();
  }else{
    design_dark();
  }
  */
//});

        //言語のドロップダウン変更するごとにイベント
        document.getElementById('lang_select').addEventListener('change', function() {
            var language = this.value;
            console.log('11言語のドロップダウン変更するごとにイベント');
            //localStorage.setItem('lang', this.value);//localStorage.setItem('lang', 'jp');
            //document.cookie = 'lang='+this.value;
            Cookies.set('lang',this.value);
            console.log('22言語のドロップダウン変更するごとにイベント');
            console.log('Language selected: ' + language);
            location.reload();// ページをリロードする
        });
        </script>
        <% if @current_email== "stepjump3333@yahoo.co.jp" %>
          <a href="notifications/new">通知作成</a>
        <% end %>
        <div class="link-div"><span class="copyright">© <%= Date.today.year %> Roll Tall</span></div>
    </div>
  </div>
</div>
</div>

app/views/shared/_user_icon.html.erb
<button  class="header-user-icon-btn">
      <% if @this_user.icon_url=="default" %>
            <img alt="default_user_icon" src="/default_user_icon.png"  class="user-icon_img">
      <% elsif @this_user.icon_url=="custom" %>
            <% if @this_user&.user_icon_image.attached? %>
                  <%= image_tag @this_user.user_icon_image ,class:"user-icon_img", alt: "user-icon_img" %>
            <% else %>
                  <!-- アイコンがアップロードされていない場合の代替コードをここに追加 -->
                  <img alt="default_user_icon" src="/default_user_icon.png"  class="user-icon_img">
            <% end %>
      <% elsif @this_user.icon_url=="gravatar" %>
            <img src="https://www.gravatar.com/avatar/<%= Digest::MD5.hexdigest(@this_user.email) %>?s=200" alt="User's Gravatar" class="user-icon_img" >
      <% end %>
</button>

app/views/shared/_user_list.html.erb
   <a href="/user/<%= @this_user.user_name %>">
        
          <%= render 'shared/user_icon' %>
          <div class="hop">
                <div class="user_ranking_username_wrap">@<%= @this_user.user_name %></div>
                <div class="user_ranking_createNum_wrap">パワー：<%= @this_user.aims.count %></div>
          </div>
    </a>
                    <% if user_signed_in? %>
                          <div class="follow_btn">
                                <% #ランキングユーザーをフォローしているか、していないかを判定

  #フォロー中かどうか判定・フォローしている場合にtrueを返し、そうでない場合にfalseを返す
  #def following?(other_user)
    #active_relationships.exists?(followed: other_user)
  #end

# 既にフォロー関係が存在するか確認
relationship = Relationship.find_by(follower_id: current_user.id, followed_id: @this_user.id)
                                if relationship
                                #if current_user.following?(user) # すでに「フォロー」している場合の処理 
                                #followerはフォローする人・followedはフォローされる人
                                %>
                                    <%= form_with(url: "/user/follow_delete", local: true, html:{ class:"follow_delete_form" ,id:"follow_delete_form"}) do |form| %>
                                          <%= form.hidden_field :follower_id, value: current_user.id %>
                                          <%= form.hidden_field :followed_id, value: @this_user.id %>
                                          <%= button_tag("フォロー中", type: 'button', class: 'follow_delete_btn follow-btn', id: 'follow_delete_btn', data: { follower_id: current_user.id, followed_id: @this_user.id }) %>

                                    <% end %> 
                                <% else # まだ「フォロー」していない場合の処理 %>
                                    <%= form_with(url: "/user/follow", local: true, html:{ class:"follow_form" ,id:"follow_form"}) do |form| %>
                                          <%= form.hidden_field :follower_id, value: current_user.id %>
                                          <%= form.hidden_field :followed_id, value: @this_user.id %>
                                          <%= button_tag("フォロー", type: 'button', class: 'follow_btn follow-btn', id: 'follow_btn', data: { follower_id: current_user.id, followed_id: @this_user.id }) %>
                                    <% end %> 
                                <% end %>
                            </div>
                    <% end %>
<% if user_signed_in? %>
<script>
$(document).ready(function() {//HTMLドキュメントが完全に読み込まれてからJavaScriptコードが実行されるようになります

//フォロー/フォロー外しを非同期で行う
$(document).on('click', '#follow_btn', function() {
      let follower_id = $(this).data('followerId');//_を外して最初大文字
      let followed_id = $(this).data('followedId');
            $(this).replaceWith('<%= button_tag("フォロー中", type: 'button', class: 'follow_delete_btn follow-btn', id: 'follow_delete_btn', data: { follower_id: current_user.id, followed_id: @this_user.id }) %>');
      $.ajax({
      type: 'POST',
      url: '/user/follow',
      data: { 
            follower_id: follower_id,
            followed_id: followed_id
            },
      success: (res) => {
            console.log("成功")
      },
      error: (res) => {
            console.log("失敗"+res.responseText)
                  $(this).replaceWith('<%= button_tag("フォロー", type: 'button', class: 'follow_btn follow-btn', id: 'follow_btn', data: { follower_id: current_user.id, followed_id: @this_user.id }) %>');
      }
      });
});

$(document).on('click', '#follow_delete_btn', function() {
      let follower_id = $(this).data('followerId');
      let followed_id = $(this).data('followedId');
            $(this).replaceWith('<%= button_tag("フォロー", type: 'button', class: 'follow_btn follow-btn', id: 'follow_btn', data: { follower_id: current_user.id, followed_id: @this_user.id }) %>');
      $.ajax({
      type: 'POST',
      url: '/user/follow_delete',
      data: { 
            follower_id: follower_id,
            followed_id: followed_id
            },
      success: (res) => {
            console.log("成功")
      },
      error: (res) => {
            console.log("失敗"+res.responseText)
                  $(this).replaceWith('<%= button_tag("フォロー中", type: 'button', class: 'follow_delete_btn follow-btn', id: 'follow_delete_btn', data: { follower_id: current_user.id, followed_id: @this_user.id }) %>');
      }
      });
});

});
</script>
<% end %>