config/routes.rb
Rails.application.routes.draw do

  #root 'top#top'
  #get '/'  => 'top#top'
  root 'aim_room#index'
  get '/'  => 'aim_room#aim_room'
  #get 'aim_room/index'

  
  

  #devise_for :users
  devise_for :users, controllers: {       # ← 恐らく最初は”devise_for:”のみの記載かと
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }, skip: :confirmations
  get 'user/regist_after' => 'user#regist_after'

  post '/user/follow/', to: 'user#follow'
  post '/user/follow_delete', to: 'user#follow_delete'



  get '/top/index'  => 'top#index'
  
  get '/top/index'  => 'top#index'

  get '/top/aim/load_more'  => 'top#load_more'
  post '/top/aim/load_more'  => 'top#load_more'
 
  
  resources :contact, only: [:new, :create]

  get 'pricing'  => 'footer#pricing'
  get 'business'  => 'footer#business'
  get 'sctl'  => 'footer#sctl'
  get 'policy'  => 'footer#policy'
  get 'terms'  => 'footer#terms'
  #get 'aim/search'
  
  #resources :aim, only: [:new, :create, :edit, :aim, :search]
  resources :aim, only: [:new, :create, :edit, :aim]
  
  #get 'aim'  =>'aim#aim'
  #get '/search/:id', to: 'aim#search'
  #get 'create'  =>'aim#create'

  get '/aim/:id', to: 'aim#aim',as: 'aim'
  get 'search'  => 'aim#search'
  post '/aim/create/', to: 'aim#create'
  get '/aim/edit/:id'  =>'aim#edit'
  post '/aim/new_confirm/'  =>'aim#confirm'
  #patch '/aim/update/:id', to: 'aim#update'
  post '/aim/update/:id', to: 'aim#update'
  post '/aim/delete/:id', to: 'aim#delete'

  post '/aim/like/', to: 'aim#like'
  post '/aim/like_delete/', to: 'aim#like_delete'

  resources :user, only: [:new, :create, :edit, :aim]
  get 'new_user'  => 'user#new_user'
  get 'mypage'  => 'user#mypage'
  get 'account_delete'  => 'user#account_delete'
  #get 'top'  => 'top#top'

  #get 'mypage'  => 'user#mypage'
  get '/user/:username', to: 'user#mypage'
  
  #resources :setting, only: [:update_password]
  get 'setting'  => 'setting#setting_page'
  post '/setting/update_mail/:id', to: 'setting#update_mail'
  post '/setting/update_username/:id', to: 'setting#update_username'
  post '/setting/update_password/:id', to: 'setting#update_password'
  patch '/setting/update_password/:id', to: 'setting#update_password'
  post '/setting/delete_user/:id', to: 'setting#delete_user'

  post '/setting/icon_type_change/:id', to: 'setting#icon_type_change'
  get '/setting/user/custom_img'  => 'setting#custom_img'
  post '/setting/upload_img/:id', to: 'setting#upload_img'

  #resources :notifications, only: [:index, :new, :create, :check]
  resources :notifications, only: [:index, :new ,:create]
  patch '/notifications/check', to: 'notifications#check'
  post '/notifications/check', to: 'notifications#check'
  post '/notifications/delete/:id', to: 'notifications#delete'
  #post '/notifications/create/', to: 'notifications#create'

  get '/llm'  => 'llm#index'
  post "/ai/generate/", to: "llm#generate"

  get '/play'  => 'play#index'
  post '/play', to: 'play#post'

  get '/sitemap' => 'sitemaps#index' 
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :message, presence: true
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      # お問い合わせ内容が保存された場合の処理
      flash[:success] = 'お問い合わせを受け付けました。'
      redirect_to new_contact_path
    else
      # お問い合わせ内容が保存されなかった場合の処理
      flash[:danger] = '正しく送信されませんでした'
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/create.html.erb
<% content_for :title do %>お問い合わせ<% end %>
<% content_for :meta_tags do %>
  <%= display_meta_tags(:noindex => true) %>
<% end %>
<%= render 'shared/header' %>
<%= render 'shared/sidemenu' %>
<h1>お問い合わせを受け付けました</h1>
<p>ありがとうございます。担当者よりご連絡いたします。</p>

app/views/contact/new.html.erb
<% content_for :title do %>お問い合わせ<% end %>
<% content_for :meta_tags do %>
  <%= display_meta_tags(:noindex => true) %>
<% end %>
<%= render 'shared/header' %>
<%= render 'shared/sidemenu' %>
<%= stylesheet_link_tag "contact" %>

<div class="footer_content_wrap">
    <h1>ご意見</h1>

    <%= form_with(model: @contact, url: contact_index_path, local: true) do |form| %>
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <%= content_tag :div, msg, class: "alert alert-#{name == :notice ? 'success' : 'danger'}" %>
        <% end %>
      <% end %>

      <% if @contact.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

          <ul>
          <% @contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.text_field :name, placeholder: "お名前", class: "name", required: true %>

      </div>

      <div class="field">
        <%= form.email_field :email, placeholder: "メールアドレス", class: "email", required: true %>
      </div>

      <div class="field">
        <%= form.text_area :message, rows: 15, placeholder: "ご入力ください。", class: "message", required: true %>

      </div>

      <div class="actions">
        <%= form.submit "送信", class: "btn btn-primary submit-btn" %>
      </div>
    <% end %>
</div>